# Generated by Django 4.2.27 on 2026-01-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chain', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apy', models.FloatField()),
                ('tvl', models.FloatField()),
                ('risk_score', models.FloatField(default=0)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defi.protocol')),
            ],
        ),
    ]
