# Generated by Django 4.2.27 on 2026-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_web3', '0001_initial'),
        ('defi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_web3.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('apy', models.FloatField()),
                ('tvl', models.FloatField(help_text='Total Value Locked')),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.AddField(
            model_name='vault',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defi.protocol'),
        ),
        migrations.AddField(
            model_name='position',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defi.vault'),
        ),
    ]
