# Generated by Django 4.2.27 on 2026-03-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0002_position_vault_protocol_risk_level_protocol_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
