from rest_framework.views import APIView
from rest_framework.response import Response
from defi.models import Protocol
from rest_framework import status
from .services.scoring import  compute_and_store_risk
from .services.llm import generate_risk_explanation
from django.shortcuts import get_object_or_404

class ProtocolRiskView(APIView):
    def post(self, request, protocol_id):
        protocol = get_object_or_404(Protocol, id=protocol_id)
        
        # 1. Fetch the latest pre-computed RiskSnapshot generated by the apscheduler
        from .models import RiskSnapshot
        latest_snapshot = RiskSnapshot.objects.filter(protocol=protocol).order_by('-created_at').first()
        
        if not latest_snapshot:
            return Response(
                {"error": "No risk data available yet. Please wait for the background data sync."}, 
                status=status.HTTP_404_NOT_FOUND
            )
            
        result = {
            "risk_score": latest_snapshot.score,
            "level": latest_snapshot.level,
            "flags": []
        }
        
        # Fetch some mocked or saved features for the LLM prompt (ideally stored in DB)
        from defi.models import Vault
        vault = Vault.objects.filter(protocol=protocol).first()
        
        features = {
            "tvl_change_24h": "Recent update",
            "liquidity_depth": vault.tvl if vault else "Unknown",
            "protocol_age_days": 365
        }
        
        # Get user details for LLM context (passed from frontend)
        user_wallet = request.data.get("wallet_address", "Unknown Wallet")
        user_balance = request.data.get("wallet_balance", "Unknown")
        
        # Generate LLM explanation using features, model output, and user data
        explanation = generate_risk_explanation(
            model_features=features,
            risk_result=result,
            user_wallet_address=user_wallet,
            user_balance=user_balance
        )
        
        return Response({
            "protocol": protocol.name,
            **result,
            "llm_explanation": explanation
        }, status = status.HTTP_200_OK)
        
        