from rest_framework.views import APIView
from rest_framework.response import Response
from defi.models import Protocol
from rest_framework import status
from .services.scoring import  compute_and_store_risk
from .services.llm import generate_risk_explanation
from django.shortcuts import get_object_or_404
from rest_framework.permissions import AllowAny

class ProtocolRiskView(APIView):
    permission_classes = [AllowAny]
    authentication_classes = []

    def post(self, request, protocol_id):
        protocol = get_object_or_404(Protocol, id=protocol_id)
        
        # 1. Fetch the latest pre-computed RiskSnapshot generated by the apscheduler
        from .models import RiskSnapshot
        latest_snapshot = RiskSnapshot.objects.filter(protocol=protocol).order_by('-created_at').first()
        
        if not latest_snapshot:
            # Generate initial risk data if none exists
            from .services.scoring import compute_and_store_risk
            from defi.models import Vault
            
            vault = Vault.objects.filter(protocol=protocol).first()
            
            # Basic default features for initial calculation
            initial_features = {
                "tvl_change_24h": -2.5, 
                "tvl_change_7d": 1.2,
                "liquidity_depth": vault.tvl if vault else 5000000,
                "utilisation_ratio": 0.65,
                "oracle_price_std": 0.02,
                "liquidation_spike_ratio": 0.1,
                "listed_at_timestamp": 1640995200  # Jan 1 2022
            }
            
            compute_and_store_risk(protocol, initial_features)
            latest_snapshot = RiskSnapshot.objects.filter(protocol=protocol).order_by('-created_at').first()
            
        result = {
            "risk_score": latest_snapshot.score,
            "level": latest_snapshot.level,
            "flags": []
        }
        
        # Fetch some mocked or saved features for the LLM prompt (ideally stored in DB)
        from defi.models import Vault
        vault = Vault.objects.filter(protocol=protocol).first()
        
        features = {
            "tvl_change_24h": "Recent update",
            "liquidity_depth": vault.tvl if vault else "Unknown",
            "protocol_age_days": 365
        }
        
        # Get user details for LLM context (passed from frontend)
        user_wallet = request.data.get("wallet_address", "Unknown Wallet")
        user_balance = request.data.get("wallet_balance", "Unknown")
        user_risk_tolerance = request.data.get("risk_tolerance", "medium")
        user_investment_goal = request.data.get("investment_goal", "Unknown")

        from .services.vector_db import get_similar_contexts
        chromadb_context_docs = get_similar_contexts(protocol.name, n_results=3)
        chromadb_context = "\\n".join(chromadb_context_docs) if chromadb_context_docs else "No historical context available."
        
        # Generate LLM explanation using features, model output, and user data
        explanation = generate_risk_explanation(
            model_features=features,
            risk_result=result,
            user_wallet_address=user_wallet,
            user_balance=user_balance,
            user_risk_tolerance=user_risk_tolerance,
            user_investment_goal=user_investment_goal,
            chromadb_context=chromadb_context
        )
        
        return Response({
            "protocol": protocol.name,
            **result,
            "llm_explanation": explanation
        }, status = status.HTTP_200_OK)

class BestProtocolView(APIView):
    permission_classes = [AllowAny]
    authentication_classes = []

    def post(self, request):
        user_wallet = request.data.get("wallet_address", "Unknown Wallet")
        user_balance = request.data.get("wallet_balance", "Unknown")
        user_risk_tolerance = request.data.get("risk_tolerance", "medium")
        user_investment_goal = request.data.get("investment_goal", "Unknown")

        from defi.models import Protocol
        from .models import RiskSnapshot
        
        protocols = Protocol.objects.all()
        protocol_scores = {}
        
        for p in protocols:
            snap = RiskSnapshot.objects.filter(protocol=p).order_by('-created_at').first()
            if snap:
                protocol_scores[p.name] = {
                    "score": snap.score,
                    "level": snap.level
                }
                
        from .services.vector_db import get_similar_contexts
        chromadb_context_docs = get_similar_contexts("market overview stable liquidity", n_results=5)
        chromadb_context = "\\n".join(chromadb_context_docs) if chromadb_context_docs else "No historical context available."
        
        from .services.llm import generate_best_protocol_explanation
        explanation = generate_best_protocol_explanation(
            protocol_scores=protocol_scores,
            user_wallet_address=user_wallet,
            user_balance=user_balance,
            user_risk_tolerance=user_risk_tolerance,
            user_investment_goal=user_investment_goal,
            chromadb_context=chromadb_context
        )
        
        best_p = "Unknown"
        best_score = float('inf')
        for name, data in protocol_scores.items():
            if data["score"] < best_score:
                best_score = data["score"]
                best_p = name
                
        return Response({
            "recommended_protocol": best_p,
            "best_score": best_score if best_score != float('inf') else 0,
            "llm_explanation": explanation,
            "all_scores": protocol_scores
        }, status=status.HTTP_200_OK)